###############################################################################
# Makefile automatically generated by Code::Blocks IDE                        #
###############################################################################

# Project:          Wolf4SDL
# Project filename: C:\sdl_src\Wolf4SDL\Wolf4SDL.cbp
# Compiler used:    GNU GCC Compiler

### Variables used in this Makefile
default_CC=mingw32-gcc.exe
default_CPP=mingw32-g++.exe
default_LD=mingw32-g++.exe
default_LIB=ar.exe
default_RESCOMP=windres.exe

### Compiler/linker options
default_GLOBAL_CFLAGS= -g
default_PROJECT_CFLAGS=
default_GLOBAL_LDFLAGS=
default_PROJECT_LDFLAGS=
default_GLOBAL_INCS= -II:/Programme/CodeBlocks/include -II:/Programme/CodeBlocks/DevPaks/include
default_PROJECT_INCS=
default_GLOBAL_LIBDIRS= -LI:/Programme/CodeBlocks/lib -LI:/Programme/CodeBlocks/DevPaks/lib
default_PROJECT_LIBDIRS=
default_GLOBAL_LIBS=
default_PROJECT_LIBS= -lmingw32 -lSDLmain -lSDL I:\Programme\CodeBlocks\lib\SDL_mixer.lib

### Targets compiler flags
default_CFLAGS= $(default_PROJECT_CFLAGS) $(default_GLOBAL_CFLAGS)

### Targets linker flags
default_LDFLAGS= $(default_PROJECT_LDFLAGS) $(default_GLOBAL_LDFLAGS)

### Targets include directories
default_INCS= $(default_PROJECT_INCS) $(default_GLOBAL_INCS)

### Targets library directories
default_LIBDIRS= $(default_PROJECT_LIBDIRS) $(default_GLOBAL_LIBDIRS)

### Targets libraries
default_LIBS= $(default_PROJECT_LIBS) $(default_GLOBAL_LIBS)

###############################################################################
#         You shouldn't need to modify anything beyond this point             #
###############################################################################

### Resources used in this Makefile
default_RESOURCE=

### Objects used in this Makefile
default_OBJS=.objs/id_vh.o .objs/fmopl.o .objs/id_ca.o .objs/id_in.o .objs/id_pm.o .objs/id_sd.o .objs/id_us_1.o .objs/Gamepal3d.o .objs/id_vl.o .objs/signon.o .objs/wl_act1.o .objs/wl_act2.o .objs/wl_agent.o .objs/wl_debug.o .objs/wl_draw.o .objs/wl_game.o .objs/wl_inter.o .objs/wl_main.o .objs/wl_menu.o .objs/wl_play.o .objs/wl_state.o .objs/wl_text.o
default_LINKOBJS=$(default_OBJS)
default_DEPS=.deps/id_vh.d .deps/fmopl.d .deps/id_ca.d .deps/id_in.d .deps/id_pm.d .deps/id_sd.d .deps/id_us_1.d .deps/Gamepal3d.d .deps/id_vl.d .deps/signon.d .deps/wl_act1.d .deps/wl_act2.d .deps/wl_agent.d .deps/wl_debug.d .deps/wl_draw.d .deps/wl_game.d .deps/wl_inter.d .deps/wl_main.d .deps/wl_menu.d .deps/wl_play.d .deps/wl_state.d .deps/wl_text.d

### The targets of this project
default_BIN=SDLapp.exe

.PHONY: all all-before all-custom all-after clean clean-custom distclean distclean-custom depend_default default-before default-after

all: all-before default all-after


dist:
	@zip Wolf4SDL.cbp.zip Wolf4SDL.cbp Makefile Gamepal3d.cpp audiosod.h audiowl6.h f_spear.h fmopl.cpp fmopl.h foreign.h gfxv_apo.h gfxv_sod.h gfxv_wl6.h id_ca.cpp id_ca.h id_in.cpp id_in.h id_pm.cpp id_sd.cpp id_sd.h id_us.h id_us_1.cpp id_vh.cpp id_vh.h id_vl.cpp id_vl.h signon.cpp wl_act1.cpp wl_act2.cpp wl_agent.cpp wl_debug.cpp wl_def.h wl_draw.cpp wl_game.cpp wl_inter.cpp wl_main.cpp wl_menu.cpp wl_menu.h wl_play.cpp wl_state.cpp wl_text.cpp

clean_default:
	@echo Cleaning target "default"...
	@$(RM) $(default_BIN) $(default_OBJS) $(default_RESOURCE)

distclean_default:
	@echo Dist-cleaning target "default"...
	@$(RM) $(default_BIN) $(default_OBJS) $(default_DEPS) $(default_RESOURCE)

clean: clean_default

distclean: distclean_default

depend_default_DIRS:
	-@if not exist ".deps\." mkdir ".deps"

depend_default: depend_default_DIRS $(default_DEPS)

depend: depend_default

default_DIRS:
	-@if not exist ".objs\." mkdir ".objs"

default: depend_default default_DIRS default-before $(default_BIN) default-after

$(default_BIN): $(default_LINKOBJS) $(default_RESOURCE)
	@echo Linking executable "SDLapp.exe"...
	@$(default_LD) $(default_LIBDIRS) -o $(default_BIN) $(default_LINKOBJS) $(default_RESOURCE) $(default_LDFLAGS) $(default_LIBS)


.deps/id_vh.d: id_vh.cpp
	@echo Calculating dependencies for "id_vh.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/id_vh.d -MT .objs/id_vh.o $(default_INCS) id_vh.cpp

.objs/id_vh.o: .deps/id_vh.d
	@echo Compiling "id_vh.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c id_vh.cpp -o .objs/id_vh.o

.deps/fmopl.d: fmopl.cpp
	@echo Calculating dependencies for "fmopl.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/fmopl.d -MT .objs/fmopl.o $(default_INCS) fmopl.cpp

.objs/fmopl.o: .deps/fmopl.d
	@echo Compiling "fmopl.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c fmopl.cpp -o .objs/fmopl.o

.deps/id_ca.d: id_ca.cpp
	@echo Calculating dependencies for "id_ca.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/id_ca.d -MT .objs/id_ca.o $(default_INCS) id_ca.cpp

.objs/id_ca.o: .deps/id_ca.d
	@echo Compiling "id_ca.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c id_ca.cpp -o .objs/id_ca.o

.deps/id_in.d: id_in.cpp
	@echo Calculating dependencies for "id_in.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/id_in.d -MT .objs/id_in.o $(default_INCS) id_in.cpp

.objs/id_in.o: .deps/id_in.d
	@echo Compiling "id_in.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c id_in.cpp -o .objs/id_in.o

.deps/id_pm.d: id_pm.cpp
	@echo Calculating dependencies for "id_pm.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/id_pm.d -MT .objs/id_pm.o $(default_INCS) id_pm.cpp

.objs/id_pm.o: .deps/id_pm.d
	@echo Compiling "id_pm.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c id_pm.cpp -o .objs/id_pm.o

.deps/id_sd.d: id_sd.cpp
	@echo Calculating dependencies for "id_sd.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/id_sd.d -MT .objs/id_sd.o $(default_INCS) id_sd.cpp

.objs/id_sd.o: .deps/id_sd.d
	@echo Compiling "id_sd.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c id_sd.cpp -o .objs/id_sd.o

.deps/id_us_1.d: id_us_1.cpp
	@echo Calculating dependencies for "id_us_1.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/id_us_1.d -MT .objs/id_us_1.o $(default_INCS) id_us_1.cpp

.objs/id_us_1.o: .deps/id_us_1.d
	@echo Compiling "id_us_1.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c id_us_1.cpp -o .objs/id_us_1.o

.deps/Gamepal3d.d: Gamepal3d.cpp
	@echo Calculating dependencies for "Gamepal3d.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/Gamepal3d.d -MT .objs/Gamepal3d.o $(default_INCS) Gamepal3d.cpp

.objs/Gamepal3d.o: .deps/Gamepal3d.d
	@echo Compiling "Gamepal3d.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c Gamepal3d.cpp -o .objs/Gamepal3d.o

.deps/id_vl.d: id_vl.cpp
	@echo Calculating dependencies for "id_vl.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/id_vl.d -MT .objs/id_vl.o $(default_INCS) id_vl.cpp

.objs/id_vl.o: .deps/id_vl.d
	@echo Compiling "id_vl.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c id_vl.cpp -o .objs/id_vl.o

.deps/signon.d: signon.cpp
	@echo Calculating dependencies for "signon.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/signon.d -MT .objs/signon.o $(default_INCS) signon.cpp

.objs/signon.o: .deps/signon.d
	@echo Compiling "signon.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c signon.cpp -o .objs/signon.o

.deps/wl_act1.d: wl_act1.cpp
	@echo Calculating dependencies for "wl_act1.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_act1.d -MT .objs/wl_act1.o $(default_INCS) wl_act1.cpp

.objs/wl_act1.o: .deps/wl_act1.d
	@echo Compiling "wl_act1.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_act1.cpp -o .objs/wl_act1.o

.deps/wl_act2.d: wl_act2.cpp
	@echo Calculating dependencies for "wl_act2.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_act2.d -MT .objs/wl_act2.o $(default_INCS) wl_act2.cpp

.objs/wl_act2.o: .deps/wl_act2.d
	@echo Compiling "wl_act2.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_act2.cpp -o .objs/wl_act2.o

.deps/wl_agent.d: wl_agent.cpp
	@echo Calculating dependencies for "wl_agent.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_agent.d -MT .objs/wl_agent.o $(default_INCS) wl_agent.cpp

.objs/wl_agent.o: .deps/wl_agent.d
	@echo Compiling "wl_agent.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_agent.cpp -o .objs/wl_agent.o

.deps/wl_debug.d: wl_debug.cpp
	@echo Calculating dependencies for "wl_debug.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_debug.d -MT .objs/wl_debug.o $(default_INCS) wl_debug.cpp

.objs/wl_debug.o: .deps/wl_debug.d
	@echo Compiling "wl_debug.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_debug.cpp -o .objs/wl_debug.o

.deps/wl_draw.d: wl_draw.cpp
	@echo Calculating dependencies for "wl_draw.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_draw.d -MT .objs/wl_draw.o $(default_INCS) wl_draw.cpp

.objs/wl_draw.o: .deps/wl_draw.d
	@echo Compiling "wl_draw.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_draw.cpp -o .objs/wl_draw.o

.deps/wl_game.d: wl_game.cpp
	@echo Calculating dependencies for "wl_game.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_game.d -MT .objs/wl_game.o $(default_INCS) wl_game.cpp

.objs/wl_game.o: .deps/wl_game.d
	@echo Compiling "wl_game.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_game.cpp -o .objs/wl_game.o

.deps/wl_inter.d: wl_inter.cpp
	@echo Calculating dependencies for "wl_inter.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_inter.d -MT .objs/wl_inter.o $(default_INCS) wl_inter.cpp

.objs/wl_inter.o: .deps/wl_inter.d
	@echo Compiling "wl_inter.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_inter.cpp -o .objs/wl_inter.o

.deps/wl_main.d: wl_main.cpp
	@echo Calculating dependencies for "wl_main.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_main.d -MT .objs/wl_main.o $(default_INCS) wl_main.cpp

.objs/wl_main.o: .deps/wl_main.d
	@echo Compiling "wl_main.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_main.cpp -o .objs/wl_main.o

.deps/wl_menu.d: wl_menu.cpp
	@echo Calculating dependencies for "wl_menu.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_menu.d -MT .objs/wl_menu.o $(default_INCS) wl_menu.cpp

.objs/wl_menu.o: .deps/wl_menu.d
	@echo Compiling "wl_menu.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_menu.cpp -o .objs/wl_menu.o

.deps/wl_play.d: wl_play.cpp
	@echo Calculating dependencies for "wl_play.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_play.d -MT .objs/wl_play.o $(default_INCS) wl_play.cpp

.objs/wl_play.o: .deps/wl_play.d
	@echo Compiling "wl_play.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_play.cpp -o .objs/wl_play.o

.deps/wl_state.d: wl_state.cpp
	@echo Calculating dependencies for "wl_state.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_state.d -MT .objs/wl_state.o $(default_INCS) wl_state.cpp

.objs/wl_state.o: .deps/wl_state.d
	@echo Compiling "wl_state.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_state.cpp -o .objs/wl_state.o

.deps/wl_text.d: wl_text.cpp
	@echo Calculating dependencies for "wl_text.cpp"...
	@$(default_CPP) -MM $(default_CFLAGS) -MF .deps/wl_text.d -MT .objs/wl_text.o $(default_INCS) wl_text.cpp

.objs/wl_text.o: .deps/wl_text.d
	@echo Compiling "wl_text.cpp"...
	@$(default_CPP) $(default_CFLAGS) $(default_INCS) -c wl_text.cpp -o .objs/wl_text.o
